name: Kernel Build Lisa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          bc bison flex libssl-dev make
        sudo apt-get install -y git wget build-essential bc bison flex \
          libncurses5-dev libssl-dev curl zip unzip python-is-python3 clang

    - name: Download kernel source (Lisa r-oss)
      run: |
        git clone --depth=1 https://git.codelinaro.org/clo/la/kernel/msm-5.4.git -b LA.UM.9.16.r1-18400-MANNAR.QSSI15.0 kernel/lisa
    - name: Copy custom defconfig
      run: |
        cp $GITHUB_WORKSPACE/lisa_defconfig kernel/lisa/arch/arm64/configs/lisa_defconfig
        #cp $GITHUB_WORKSPACE/lisa_defconfig kernel/lisa/.config

    - name: Download AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
        
    - name: Build kernel
      run: |
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        cd kernel/lisa
        mkdir -p out
        make O=out clean
        make O=out mrproper
        #make O=out ARCH=arm64 lisa_defconfig
        
        export KCFLAGS=-Wno-error
        export CFLAGS_KERNEL=-Wno-error
        export KBUILD_CFLAGS=-Wno-error

        #cp $GITHUB_WORKSPACE/lisa_defconfig kernel/lisa/.config
        make O=out ARCH=arm64 olddefconfig
        make -j$(nproc) O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-
         # concat Image.gz + dtbs
        cat out/arch/arm64/boot/Image.gz out/arch/arm64/boot/dts/qcom/*.dtb > out/arch/arm64/boot/Image.gz-dtb
        cp out/arch/arm64/boot/Image.gz-dtb $GITHUB_WORKSPACE/AnyKernel3/
        cp out/arch/arm64/boot/Image.gz $GITHUB_WORKSPACE/AnyKernel3/
        
    - name: Package AnyKernel3 zip
      run: |
        cd AnyKernel3
        zip -r9 Lisa-Kernel-NH.zip * -x .git README.md *placeholder

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Lisa-Kernel-NH
        path: AnyKernel3/Lisa-Kernel-NH.zip
        
