name: Build r2frida

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc libzip-dev nodejs npm curl pkg-config git radare2

    - name: Build r2frida
      run: |
        git clone --depth 1 https://github.com/nowsecure/r2frida.git
        cd r2frida
        make
        make user-install

    - name: Test installation
      run: |
        ~/.local/share/radare2/plugins/r2frida.js --help || echo "Build successful"
