name: Build r2frida Android ARM64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r25c
      ANDROID_API: 33
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk
      ANDROID_R2_PREFIX: ${{ github.workspace }}/android-r2

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Install Ubuntu dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git pkg-config python3 python3-pip clang libssl-dev libelf-dev unzip curl

    # 3️⃣ Install meson and ninja (needed for Frida)
    - name: Install Python build tools
      run: |
        python3 -m pip install --user meson ninja
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    # 4️⃣ Download Android NDK
    - name: Download Android NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip -d $ANDROID_NDK_HOME

    # 5️⃣ Set environment for cross-compilation
    - name: Setup NDK toolchain
      run: |
        export PATH=$ANDROID_NDK_HOME/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export CC=aarch64-linux-android${ANDROID_API}-clang
        export CXX=aarch64-linux-android${ANDROID_API}-clang++
        export SYSROOT=$ANDROID_NDK_HOME/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/sysroot
        echo "CC=${CC}" >> $GITHUB_ENV
        echo "CXX=${CXX}" >> $GITHUB_ENV
        echo "SYSROOT=${SYSROOT}" >> $GITHUB_ENV

    # 6️⃣ Clone radare2
    - name: Clone radare2
      run: |
        git clone --depth=1 https://github.com/radareorg/radare2.git

    # 7️⃣ Build radare2 for Android
    - name: Build radare2 for Android
      run: |
        cd radare2
        ./configure --host=aarch64-linux-android --prefix=$ANDROID_R2_PREFIX --sysroot=$SYSROOT
        make -j$(nproc)
        make install
        cd ..

    # 8️⃣ Clone r2frida
    - name: Clone r2frida
      run: |
        git clone --depth=1 --recursive https://github.com/nowsecure/r2frida.git

    # 9️⃣ Build r2frida plugin
    - name: Build r2frida
      run: |
        cd r2frida
        make clean || true
        rm -rf node_modules ext/frida*
        export PATH=$ANDROID_R2_PREFIX/bin:$PATH
        export R2PM_OFFLINE=1
        make io_frida.so

    # 🔟 Upload artifact
    - name: Upload r2frida plugin
      uses: actions/upload-artifact@v4
      with:
        name: r2frida-android-arm64
        path: r2frida/src/io_frida.so
