name: Build r2frida

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc g++ libzip-dev nodejs npm curl pkg-config git libssl-dev

    - name: Install radare2 from source
      run: |
        git clone --depth 1 https://github.com/radareorg/radare2.git
        cd radare2
        sys/install.sh
        r2 -v

    - name: Clone and build r2frida
      run: |
        git clone --depth 1 https://github.com/nowsecure/r2frida.git
        cd r2frida
        ./configure
        make
        make user-instail

    - name: Test r2frida
      run: |
        ~/.local/share/radare2/plugins/r2frida.js --version || echo "r2frida built successfully"
