name: Build r2frida Android ARM64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r25c
      ANDROID_API: 33
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk

    steps:
    # 1️⃣ Checkout surse
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Instalare dependențe Ubuntu
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git pkg-config python3 python3-pip clang libssl-dev libelf-dev unzip curl radare2

    # 3️⃣ Descarcă și dezarhivează Android NDK
    - name: Download Android NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        unzip android-ndk-${ANDROID_NDK_VERSION}-linux.zip -d $GITHUB_WORKSPACE/android-ndk

    # 4️⃣ Setare PATH pentru NDK și toolchain
    - name: Setup NDK toolchain
      run: |
        echo "$ANDROID_NDK_HOME/android-ndk-${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        export CC=aarch64-linux-android${ANDROID_API}-clang
        export CXX=aarch64-linux-android${ANDROID_API}-clang++

    # 5️⃣ Clone r2frida
    - name: Clone r2frida
      run: |
        git clone --depth=1 --recursive https://github.com/nowsecure/r2frida.git

    # 6️⃣ Build r2frida
    - name: Build r2frida
      run: |
        cd r2frida
        make clean || true
        rm -rf node_modules ext/frida*
        export R2PM_OFFLINE=1
        make io_frida.so

    # 7️⃣ Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: r2frida-android-arm64
        path: r2frida/src/io_frida.so
        
